version: 2.1
defaults:
  working_directory: ~/project
orbs:
  node: circleci/node@4.7

jobs:
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Run tests
          command: yarn test
      #- run:
      #    name: Publish to NPM
      #    command: |
      #      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      #      npm publish --access public
            
workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/